### ISSUE TITLE
Dynamic Guidance

### ISSUE THREAD

**Issue by zhenyuan1234** [pq-yang/PGDiff#8]
Hi, is the dynamic guidance scheme used in the blind face restoration task? Thanks!

**Comment by pq-yang** [comment]
Hi @zhenyuan1234 , the dynamic guidance weight $s_{norm}$ is not used in the blind face restoration task by default, since a constant guidance weight is good enough for this task. 

As for the multiple gradient steps, you may employ this by setting `N`, `s_start`, and `s_end` in the inference script. Please refer to [line 253](https://github.com/pq-yang/PGDiff/blob/8634514f72d90d8ff79ef7c0941ad3c89599a97d/inference_pgdiff.py#L253) - [line 255](https://github.com/pq-yang/PGDiff/blob/8634514f72d90d8ff79ef7c0941ad3c89599a97d/inference_pgdiff.py#L255) for more details. To accelerate the inference process, we set `N=1` by default.
